CREATE TABLE team (
	id INT NOT NULL AUTO_INCREMENT,
	nano_id VARCHAR(22) NOT NULL UNIQUE,
	team_owner INT NOT NULL,
	team_name VARCHAR(64) NOT NULL UNIQUE,
	team_desc TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id),
	FOREIGN KEY (team_owner) REFERENCES player(id)
);
